// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(GameLogContext))]
    partial class GameLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Entities.GameEntity", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateReleased")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("GameEntities");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            DateCompleted = new DateOnly(2024, 3, 15),
                            DateReleased = new DateOnly(2011, 9, 22),
                            DateStarted = new DateOnly(2024, 2, 1),
                            Rating = 8,
                            Review = "Amazing difficulty. Bit confusing at times.",
                            Title = "Dark Souls 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
